USE PROVA
-- EX 3

--DROP TABLE FUNCIONÁRIO
--DROP TABLE DEPARTAMENTO

CREATE TABLE DEPARTAMENTO
(
DDEPARTAMENTO INT IDENTITY PRIMARY KEY,
NOME VARCHAR(50),
LOCALIDADE INT -- LOCAL ERA UMA PALAVRA RESERVADA
);
GO
CREATE TABLE GRADESALARIAL(
GRADE INT IDENTITY PRIMARY KEY,
SAL_MIN INT,
SAL_MAX INT
);
GO
CREATE TABLE FUNCIONÁRIO  (
    EDV INT PRIMARY KEY,
	NOME VARCHAR(255),
	LIDER VARCHAR(255),
    DATACONTRATACAO DATE NOT NULL,
    SALARIO FLOAT,
	DEPARTAMENTO INT
    FOREIGN KEY (DEPARTAMENTO) REFERENCES DEPARTAMENTO(DDEPARTAMENTO)
);

SELECT * FROM DEPARTAMENTO

INSERT INTO DEPARTAMENTO(NOME,LOCALIDADE) VALUES ('REMAN',104)
INSERT INTO DEPARTAMENTO(NOME,LOCALIDADE) VALUES ('ICO',101)
INSERT INTO DEPARTAMENTO(NOME,LOCALIDADE) VALUES ('ETS',401)
INSERT INTO DEPARTAMENTO(NOME,LOCALIDADE) VALUES ('FCM',303)
INSERT INTO DEPARTAMENTO(NOME,LOCALIDADE) VALUES ('INOVE',303)


INSERT INTO GRADESALARIAL(SAL_MIN, SAL_MAX) VALUES (1500, 4000)
INSERT INTO GRADESALARIAL(SAL_MIN, SAL_MAX) VALUES (4001, 9000)
INSERT INTO GRADESALARIAL(SAL_MIN, SAL_MAX) VALUES (9001, 22000)
INSERT INTO GRADESALARIAL(SAL_MIN, SAL_MAX) VALUES (1500, 4000)
INSERT INTO GRADESALARIAL(SAL_MIN, SAL_MAX) VALUES (22001, 50000)

SELECT * FROM FUNCIONÁRIO

INSERT INTO FUNCIONÁRIO(EDV, NOME, LIDER, DATACONTRATACAO, SALARIO, DEPARTAMENTO) VALUES(92890148, 'Edna Carvalho', 'Andrea', '1990-02-24', 19000, (SELECT DDEPARTAMENTO FROM DEPARTAMENTO WHERE DDEPARTAMENTO = 1))
INSERT INTO FUNCIONÁRIO(EDV, NOME, LIDER, DATACONTRATACAO, SALARIO, DEPARTAMENTO) VALUES(92790062, 'João Manfredo', 'Andrea', '2001-09-26', 12500,(SELECT DDEPARTAMENTO FROM DEPARTAMENTO WHERE DDEPARTAMENTO = 1))
INSERT INTO FUNCIONÁRIO(EDV, NOME, LIDER, DATACONTRATACAO, SALARIO, DEPARTAMENTO) VALUES(91004090, 'Débora Junior', 'Andrea', '1999-03-02', 15600, (SELECT DDEPARTAMENTO FROM DEPARTAMENTO WHERE DDEPARTAMENTO = 1))
INSERT INTO FUNCIONÁRIO(EDV, NOME, LIDER, DATACONTRATACAO, SALARIO, DEPARTAMENTO) VALUES(94566222, 'Carla Rodrigues', 'Andrea', '1990-10-04', 20000, (SELECT DDEPARTAMENTO FROM DEPARTAMENTO WHERE DDEPARTAMENTO = 1))
INSERT INTO FUNCIONÁRIO(EDV, NOME, LIDER, DATACONTRATACAO, SALARIO, DEPARTAMENTO) VALUES(96334100, 'Maciel Oliveira', 'Andrea', '1995-12-06', 16500, (SELECT DDEPARTAMENTO FROM DEPARTAMENTO WHERE DDEPARTAMENTO = 1))

INSERT INTO FUNCIONÁRIO(EDV, NOME, LIDER, DATACONTRATACAO, SALARIO, DEPARTAMENTO) VALUES(97885245, 'Guilherme Gonçalves', 'Marcos', '2010-05-13', 9000, (SELECT DDEPARTAMENTO FROM DEPARTAMENTO WHERE DDEPARTAMENTO = 2))
INSERT INTO FUNCIONÁRIO(EDV, NOME, LIDER, DATACONTRATACAO, SALARIO, DEPARTAMENTO) VALUES(92894706, 'Jessica Lima', 'Marcos', '2015-08-14', 25678, (SELECT DDEPARTAMENTO FROM DEPARTAMENTO WHERE DDEPARTAMENTO = 2))
INSERT INTO FUNCIONÁRIO(EDV, NOME, LIDER, DATACONTRATACAO, SALARIO, DEPARTAMENTO) VALUES(91450032, 'Isabella Machado', 'Marcos', '1993-01-22', 10900, (SELECT DDEPARTAMENTO FROM DEPARTAMENTO WHERE DDEPARTAMENTO = 2))
INSERT INTO FUNCIONÁRIO(EDV, NOME, LIDER, DATACONTRATACAO, SALARIO, DEPARTAMENTO) VALUES(94661932, 'Carlo Daniel', 'Lucio', '1990-01-31', 13750, (SELECT DDEPARTAMENTO FROM DEPARTAMENTO WHERE DDEPARTAMENTO = 2))
INSERT INTO FUNCIONÁRIO(EDV, NOME, LIDER, DATACONTRATACAO, SALARIO, DEPARTAMENTO) VALUES(95780634, 'Maria Santana', 'Lucio', '2015-09-05', 8000, (SELECT DDEPARTAMENTO FROM DEPARTAMENTO WHERE DDEPARTAMENTO = 2))

INSERT INTO FUNCIONÁRIO(EDV, NOME, LIDER, DATACONTRATACAO, SALARIO, DEPARTAMENTO) VALUES(97881945, 'Dominic Ferreira', 'Pietra', '2020-02-09', 2000,(SELECT DDEPARTAMENTO FROM DEPARTAMENTO WHERE DDEPARTAMENTO = 3))
INSERT INTO FUNCIONÁRIO(EDV, NOME, LIDER, DATACONTRATACAO, SALARIO, DEPARTAMENTO) VALUES(98490620, 'Daniela Silva', 'Pietra', '2020-02-09', 1500, (SELECT DDEPARTAMENTO FROM DEPARTAMENTO WHERE DDEPARTAMENTO = 3))
INSERT INTO FUNCIONÁRIO(EDV, NOME, LIDER, DATACONTRATACAO, SALARIO, DEPARTAMENTO) VALUES(96854299, 'Felipe Augusto', 'Pietra', '2020-02-09', 1600, (SELECT DDEPARTAMENTO FROM DEPARTAMENTO WHERE DDEPARTAMENTO = 3))
INSERT INTO FUNCIONÁRIO(EDV, NOME, LIDER, DATACONTRATACAO, SALARIO, DEPARTAMENTO) VALUES(97805503, 'Natalia Reis', 'Pietra', '2019-06-14', 2200, (SELECT DDEPARTAMENTO FROM DEPARTAMENTO WHERE DDEPARTAMENTO = 3))
INSERT INTO FUNCIONÁRIO(EDV, NOME, LIDER, DATACONTRATACAO, SALARIO, DEPARTAMENTO) VALUES(90103456, 'Thiago Dias', 'Pietra', '2018-08-24', 2800, (SELECT DDEPARTAMENTO FROM DEPARTAMENTO WHERE DDEPARTAMENTO = 3))
INSERT INTO FUNCIONÁRIO(EDV, NOME, LIDER, DATACONTRATACAO, SALARIO, DEPARTAMENTO) VALUES(98462157, 'Lorena Ray', 'Pietra', '2017-02-25', 1900, (SELECT DDEPARTAMENTO FROM DEPARTAMENTO WHERE DDEPARTAMENTO = 3))
INSERT INTO FUNCIONÁRIO(EDV, NOME, LIDER, DATACONTRATACAO, SALARIO, DEPARTAMENTO) VALUES(95482340, 'Natanael Brasil', 'Pietra', '2020-06-03', 3500, (SELECT DDEPARTAMENTO FROM DEPARTAMENTO WHERE DDEPARTAMENTO = 3))


INSERT INTO FUNCIONÁRIO(EDV, NOME, LIDER, DATACONTRATACAO, SALARIO, DEPARTAMENTO) VALUES(96314782, 'Ana Mass', 'Captu', '1997-02-19', 3600,(SELECT DDEPARTAMENTO FROM DEPARTAMENTO WHERE DDEPARTAMENTO = 4))
INSERT INTO FUNCIONÁRIO(EDV, NOME, LIDER, DATACONTRATACAO, SALARIO, DEPARTAMENTO) VALUES(97854318, 'Otávio Luis', 'Captu', '2017-05-19', 9200, (SELECT DDEPARTAMENTO FROM DEPARTAMENTO WHERE DDEPARTAMENTO = 4))
INSERT INTO FUNCIONÁRIO(EDV, NOME, LIDER, DATACONTRATACAO, SALARIO, DEPARTAMENTO) VALUES(94862122, 'Luisa Otávia', 'Captu', '2002-11-11', 10500, (SELECT DDEPARTAMENTO FROM DEPARTAMENTO WHERE DDEPARTAMENTO = 4))
INSERT INTO FUNCIONÁRIO(EDV, NOME, LIDER, DATACONTRATACAO, SALARIO, DEPARTAMENTO) VALUES(97864320, 'Lucas Moura', 'Captu', '1990-08-29', 6600, (SELECT DDEPARTAMENTO FROM DEPARTAMENTO WHERE DDEPARTAMENTO = 4))
INSERT INTO FUNCIONÁRIO(EDV, NOME, LIDER, DATACONTRATACAO, SALARIO, DEPARTAMENTO) VALUES(96315782, 'Fernanda Lacerda', 'Captu', '1999-12-17', 2900, (SELECT DDEPARTAMENTO FROM DEPARTAMENTO WHERE DDEPARTAMENTO = 4))
INSERT INTO FUNCIONÁRIO(EDV, NOME, LIDER, DATACONTRATACAO, SALARIO, DEPARTAMENTO) VALUES(97546210, 'Caroline Adeus', 'Captu', '2018-02-19', 4555, (SELECT DDEPARTAMENTO FROM DEPARTAMENTO WHERE DDEPARTAMENTO = 4))
INSERT INTO FUNCIONÁRIO(EDV, NOME, LIDER, DATACONTRATACAO, SALARIO, DEPARTAMENTO) VALUES(94621573, 'Marco Valastro', 'Captu', '2003-03-30', 7000, (SELECT DDEPARTAMENTO FROM DEPARTAMENTO WHERE DDEPARTAMENTO = 4))

INSERT INTO FUNCIONÁRIO(EDV, NOME, LIDER, DATACONTRATACAO, SALARIO, DEPARTAMENTO) VALUES(96548432, 'Valdemir Cantante', 'Jonas', '2020-03-15', 1200, (SELECT DDEPARTAMENTO FROM DEPARTAMENTO WHERE DDEPARTAMENTO = 5))
INSERT INTO FUNCIONÁRIO(EDV, NOME, LIDER, DATACONTRATACAO, SALARIO, DEPARTAMENTO) VALUES(97511020, 'Eduarda Souza', 'Jonas', '2011-08-14', 1100, (SELECT DDEPARTAMENTO FROM DEPARTAMENTO WHERE DDEPARTAMENTO = 5))
INSERT INTO FUNCIONÁRIO(EDV, NOME, LIDER, DATACONTRATACAO, SALARIO, DEPARTAMENTO) VALUES(96410654, 'Allan Jonas', 'Felipe', '2008-06-17', 3200, (SELECT DDEPARTAMENTO FROM DEPARTAMENTO WHERE DDEPARTAMENTO = 5))
INSERT INTO FUNCIONÁRIO(EDV, NOME, LIDER, DATACONTRATACAO, SALARIO, DEPARTAMENTO) VALUES(95645012, 'Diana Jones', 'Felipe', '2002-09-24', 2050, (SELECT DDEPARTAMENTO FROM DEPARTAMENTO WHERE DDEPARTAMENTO = 5))
INSERT INTO FUNCIONÁRIO(EDV, NOME, LIDER, DATACONTRATACAO, SALARIO, DEPARTAMENTO) VALUES(94746054, 'Mario Bros', 'Felipe', '1990-01-18', 25600, (SELECT DDEPARTAMENTO FROM DEPARTAMENTO WHERE DDEPARTAMENTO = 5))
INSERT INTO FUNCIONÁRIO(EDV, NOME, LIDER, DATACONTRATACAO, SALARIO, DEPARTAMENTO) VALUES(92085478, 'Aline Franco', 'Jonas', '1996-05-05', 3700, (SELECT DDEPARTAMENTO FROM DEPARTAMENTO WHERE DDEPARTAMENTO = 5))

SELECT
D.NOME AS 'NOME DEPARTAMENTO',
MAX(F.SALARIO) AS 'MÁXIMO',
MIN(F.SALARIO) AS 'MÍNIMO',
SUM(F.SALARIO)/COUNT(F.SALARIO) AS 'MÉDIA'
FROM FUNCIONÁRIO AS F
INNER JOIN DEPARTAMENTO AS D
ON F.DEPARTAMENTO = D.DDEPARTAMENTO
GROUP BY D.NOME


CREATE FUNCTION EXIBICAO(@SALARIO INT)
RETURNS TABLE AS 
RETURN
(
SELECT
	D.NOME AS 'DEPARTAMENTO' ,
	COUNT(F.DEPARTAMENTO) AS 'QUANTIDADE DE PESSOAS'
	FROM FUNCIONÁRIO AS F
	INNER JOIN DEPARTAMENTO AS D
	ON F.DEPARTAMENTO = D.DDEPARTAMENTO 
	WHERE SALARIO > @SALARIO 
	GROUP BY D.NOME
)

SELECT * FROM EXIBICAO(2000)

GO
SELECT TOP 1
NOME,
LIDER,
SALARIO,
CONVERT(VARCHAR(8),DATACONTRATACAO, 103),
CASE WHEN SALARIO > (SELECT SAL_MIN FROM GRADESALARIAL WHERE GRADE = 1 ) AND SALARIO < (SELECT SAL_MAX FROM GRADESALARIAL WHERE GRADE = 1 )  THEN '1'
ELSE (CASE WHEN SALARIO > (SELECT SAL_MIN FROM GRADESALARIAL WHERE GRADE = 2 ) AND SALARIO < (SELECT SAL_MAX FROM GRADESALARIAL WHERE GRADE = 2 )  THEN '2' 
ELSE (CASE WHEN SALARIO > (SELECT SAL_MIN FROM GRADESALARIAL WHERE GRADE = 3 ) AND SALARIO < (SELECT SAL_MAX FROM GRADESALARIAL WHERE GRADE = 3 )  THEN '3' 
ELSE (CASE WHEN SALARIO > (SELECT SAL_MIN FROM GRADESALARIAL WHERE GRADE = 4 ) AND SALARIO < (SELECT SAL_MAX FROM GRADESALARIAL WHERE GRADE = 4 )  THEN '4' 
ELSE 'NEHNHUM' END AS 'GRADE'
FROM FUNCIONÁRIO
ORDER BY DATACONTRATACAO ASC
--SELECT(DATACONTRATACAO = MIN(DATACONTRATACAO))



