CREATE DATABASE MECANICA; USE MECANICA;

DROP TABLE SERVICE;
SHOW TABLES;

CREATE TABLE C_CLIENT(
IDCLIENT INT NOT NULL PRIMARY KEY auto_increment,
CPF INT NOT NULL,
CNAME NVARCHAR(60) NOT NULL,
ADRESS VARCHAR(255),
TEL VARCHAR(60)
)default charset utf8mb4;

CREATE TABLE VEHICLES(
IDVEHICLE INT NOT NULL PRIMARY KEY auto_increment,
IDCLIENT INT,
BRAND VARCHAR(60),
MODEL VARCHAR(60),
V_YEAR VARCHAR(60),
PLATE VARCHAR(60),
FOREIGN KEY (IDCLIENT) REFERENCES C_CLIENT(IDCLIENT)
)default charset utf8mb4;

CREATE TABLE SERVICE_ORDER(
IDSERVICE_ORDER INT NOT NULL PRIMARY KEY auto_increment,
IDVEHICLE INT NOT NULL,
DATE_ENTRADA DATETIME NOT NULL,
DATE_SAIDA DATETIME NOT NULL,
foreign key (IDVEHICLE) REFERENCES VEHICLES(IDVEHICLE)
)default CHARSET utf8mb4;

CREATE TABLE SERVICE(
IDSERVICE INT NOT NULL primary KEY auto_increment,
S_NAME VARCHAR(60),
S_DESCRIPTION VARCHAR(255),
PRICE FLOAT
)DEFAULT CHARSET utf8mb4;

DROP TABLE SERVICE_ORDER;
DROP TABLE SERVICE_DETAILS;

CREATE TABLE SERVICE_DETAILS(
IDSERVICE_DATAILS INT NOT NULL PRIMARY KEY auto_increment,
IDSERVICE INT NOT NULL,
IDITEM INT,
IDSERVICE_ORDER INT NOT NULL,
SERVICE_STATUS VARCHAR(60) NOT NULL,
foreign key (IDSERVICE_ORDER) REFERENCES SERVICE_ORDER(IDSERVICE_ORDER),
foreign key (IDSERVICE) REFERENCES SERVICE(IDSERVICE),
foreign key (IDITEM) REFERENCES ITEM(IDITEM)
)DEFAULT CHARSET utf8mb4;

CREATE TABLE ITEM(
IDITEM INT NOT NULL PRIMARY KEY auto_increment,
I_NAME VARCHAR(60) NOT NULL,
PRICE FLOAT NOT NULL
)DEFAULT CHARSET utf8mb4;

CREATE TABLE ITEMS_DETAILS(
IDITEMS_DETAILS INT NOT NULL PRIMARY KEY auto_increment,
IDITEM INT NOT NULL,
IDSERVICE_ORDER INT NOT NULL,
QUANTIDADE INT NOT NULL,
O_STATUS VARCHAR(60) NOT NULL,
DETAILS VARCHAR(255),
OBSERVACAO VARCHAR(255),
foreign key (IDITEM) REFERENCES ITEM(IDITEM)
) default CHARSET utf8mb4;


